device: "cuda:0"
scene_dir: "./Env/scene_file"
scene_name: "Eudora"
episode_num: 10
visualize_freq: 30
local_occ_net:
    dropout: 0.5
    use_pretrained_resnet18: True
environment:
    scene_cfg:
        scene_file: ""
        random_seed: 1234
        allow_sliding: True
        max_episode_length: 500
        goal_reach_eps: 0.5
    sensor_cfg:
        use_sensors: ["color_sensor"]
        sensor_height: 0.6
        obs_width: 224
        obs_height: 224
        enable_panorama: True
        clip_depth_max: 0.0
        enable_noisy_observation: False
        noise_intensity: 0.1
    map_cfg:
        top_down_type: "boundary"
        meters_per_pixel: 0.01
        local_map_size: 64
        enable_local_map: True
        enable_ego_local_map: True
        show_agent: True
        show_goal: True
    agent_cfg:
        move_forward: 0.15
        turn_left: 90
        turn_right: 90
        enable_noisy_actuation: False
cmn_cfg:
    mpp: "03"
    local_map_size: 3
    forward_step_k: 2
    forward_meter: 0.1
